# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build, test, and upload prebuilds

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Install libcurl4-openssl-dev
      run: sudo apt update && sudo apt install -y libcurl4-openssl-dev
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - run: npm run fetch-deps
    - run: npm run build-transmission
    - run: npm i
    - run: npm test
    - run: npm run prebuild
    - uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.os }}
        path: ./prebuilds
