# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install libcurl4-openssl-dev
      run: sudo apt install -y libcurl4-openssl-dev
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - run: npm run fetch-deps
    - run: npm run build-transmission
    - run: npm i
    - run: npm test
      env:
        CI: true
